server:
  host: 0.0.0.0
  port: 8765
vad:
  model_dir: models/snakers4_silero-vad
  threshold: 0.5
  threshold_low: 0.2
  min_silence_duration_ms: 300
asr:
  model_dir: models/SenseVoiceSmall
  output_dir: tmp/
  delete_audio_file: true

  # DoubaoASR配置
  # 可以在这里申请相关Key等信息
  # https://console.volcengine.com/speech/app
  # DoubaoASR和DoubaoStreamASR的区别是：DoubaoASR是按次收费，DoubaoStreamASR是按时收费
  # 一般来说按次收费的更便宜，但是DoubaoStreamASR使用了大模型技术，效果更好
  # type: doubao
  # appid: 4839868160
  # access_token: ABdTkIR1DIyfI7iU6CuFHT1_2dArz-Qz
  # cluster: volcengine_input_common
  # # 热词、替换词使用流程：https://www.volcengine.com/docs/6561/155738
  # boosting_table_name: （选填）你的热词文件名称
  # correct_table_name: （选填）你的替换词文件名称
  # output_dir: tmp/